import { BaseAgent } from "./base-agent.js";
import { config, type PipelineProfile } from "../config.js";

const SYSTEM_PROMPT = `You are the CTO of an elite software engineering team. Your role is to analyze product ideas and produce comprehensive technical architecture decisions.

If the user prompt says MVP MODE or SMOKE MODE, prioritize compact local execution over exhaustive production architecture.

When given a product idea, you MUST produce a detailed technical document that includes:

## 1. System Architecture Overview
- High-level architecture diagram (ASCII)
- Component interaction diagram
- Data flow description

## 2. Technology Stack Decisions
For each layer, specify exact technologies with versions:
- Frontend: framework, state management, UI library, build tool
- Backend: language, framework, database(s), caching, message queue
- Infrastructure: containerization, deployment, monitoring
- Testing: frameworks and strategies

## 3. Database Schema
- Entity-relationship diagram (ASCII)
- Key tables/collections with fields

## 4. API Design Principles
- REST vs GraphQL decision with justification
- Authentication/authorization approach
- Rate limiting and security headers

## 5. Project Structure
- Monorepo vs polyrepo decision
- Directory structure for each service
- Key files and their purposes

## 6. Non-Functional Requirements
- Performance targets (response times, throughput)
- Scalability approach
- Security requirements
- Monitoring and observability

## 7. Development Milestones
- Phase 1: Core MVP (what to build first)
- Phase 2: Enhancement
- Phase 3: Scale

Be specific, production-ready, and opinionated. No vague recommendations.
Use modern, battle-tested technology choices for 2025.`;

export class CTOAgent extends BaseAgent {
  private readonly runtimeProfile: PipelineProfile;

  constructor(profile: PipelineProfile = config.pipeline.profile) {
    super({
      agentId: "cto",
      agentName: "CTO Agent",
      systemPrompt: SYSTEM_PROMPT,
      maxTokens: 16000,
      thinkingBudget: 10000,
      profile,
    });
    this.runtimeProfile = profile;
  }

  buildPrompt(projectIdea: string): string {
    if (this.runtimeProfile === "mvp") {
      return `Product Idea: "${projectIdea}"

MVP MODE: Produce a concise technical plan for a local-first MVP that can be generated by a small open-source coding model.

Output only these sections:
## Product Shape
- Name the product, primary user, and one core workflow.

## Local-First Stack
- Frontend: React 18 + TypeScript + Vite only.
- Backend: Express + TypeScript with in-memory storage.
- Persistence: in-memory seed data for this version; no external database.
- Integrations: none unless absolutely required by the idea.

## Data Model
- Define 1-2 core entities with TypeScript interfaces.

## API Surface
- Define GET /health and 3-5 REST endpoints under /api.

## MVP Scope
- List 3-5 must-have capabilities.
- List what is intentionally out of scope.

Keep it implementation-ready and under 900 words.`;
    }

    return `Product Idea: "${projectIdea}"

Analyze this product idea and produce a comprehensive technical architecture document.
Make definitive technology choices and justify each decision.
The output will be used by PM, Backend, and Frontend agents to implement the system.`;
  }
}
